"""empty message

Revision ID: 7543e03ac01d
Revises: aa9386d77611
Create Date: 2025-05-17 22:20:38.210413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7543e03ac01d'
down_revision = 'aa9386d77611'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(length=128), nullable=True))
        batch_op.add_column(sa.Column('preference_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('payment_id', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedido', schema=None) as batch_op:
        batch_op.drop_column('payment_id')
        batch_op.drop_column('preference_id')
        batch_op.drop_column('link')

    # ### end Alembic commands ###
