"""OBS em pedidos e clientes

Revision ID: cabeb21a7fee
Revises: 
Create Date: 2024-05-19 01:46:35.648856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cabeb21a7fee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('nome_cl', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('obs', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome_produto', sa.String(length=128), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('porcao', sa.String(length=20), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('categoria', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produtor',
    sa.Column('CPF', sa.Integer(), nullable=False),
    sa.Column('nome_pr', sa.String(length=100), nullable=False),
    sa.Column('endereco', sa.String(length=100), nullable=False),
    sa.Column('telefone', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('CPF')
    )
    op.create_table('pedido',
    sa.Column('N_pedido', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.Column('data_pedido', sa.DateTime(), nullable=False),
    sa.Column('data_entrega', sa.DateTime(), nullable=True),
    sa.Column('obs', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['cliente_id'], ['cliente.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('N_pedido')
    )
    op.create_table('registra',
    sa.Column('produtor_cpf', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.ForeignKeyConstraint(['produtor_cpf'], ['produtor.CPF'], ),
    sa.PrimaryKeyConstraint('produtor_cpf', 'produto_id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('nome', sa.String(length=127), nullable=False),
    sa.Column('preco', sa.Float(), nullable=False),
    sa.Column('qtd', sa.Integer(), nullable=False),
    sa.Column('N_pedido', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['N_pedido'], ['pedido.N_pedido'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('itens_pedido')
    op.drop_table('registra')
    op.drop_table('pedido')
    op.drop_table('produtor')
    op.drop_table('produto')
    op.drop_table('cliente')
    # ### end Alembic commands ###
